@extends('layouts.dashboard')

@section('dashboard_title', 'Report Details')

@section('dashboard_content')
<div class="d-flex justify-content-between align-items-center mb-4">
    <h4 class="mb-0">Report Details</h4>
    <a href="{{ route($backRoute) }}" class="btn btn-outline-secondary">
        <i class="bi bi-arrow-left me-2"></i>Back to Reports
    </a>
</div>

<div class="card">
    <div class="card-body">
        <div class="row g-3">
            <div class="col-md-6">
                <label class="form-label text-muted small mb-1">Report Name</label>
                <div class="fw-semibold">{{ $report->report_name ?? 'N/A' }}</div>
            </div>
            <div class="col-md-6">
                <label class="form-label text-muted small mb-1">Report Type</label>
                <div>{{ $report->report_type ?? 'N/A' }}</div>
            </div>
            <div class="col-md-6">
                <label class="form-label text-muted small mb-1">Generated At</label>
                <div>{{ optional($report->created_at)->format('M d, Y H:i') ?? 'N/A' }}</div>
            </div>
            <div class="col-md-6">
                <label class="form-label text-muted small mb-1">Generated By</label>
                <div>{{ $report->creator->name ?? 'N/A' }}</div>
            </div>
            <div class="col-12">
                <label class="form-label text-muted small mb-1">Parameters</label>
                <pre class="bg-light rounded p-3 mb-0">{{ json_encode($report->parameters ?? [], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) }}</pre>
            </div>
        </div>
    </div>
</div>
@endsection
