<?php

return [

    'enabled' => env('TIRAMIS_ENABLED', false),

    'mode' => env('TIRAMIS_MODE', 'sandbox'),

    'client' => [
        'code' => env('TIRAMIS_CLIENT_CODE', ''),
        'key' => env('TIRAMIS_CLIENT_KEY', ''),
        'company_code' => env('TIRAMIS_COMPANY_CODE', ''),
        'system_code' => env('TIRAMIS_SYSTEM_CODE', 'SYS0001'),
        'callback_url' => env('TIRAMIS_CALLBACK_URL', ''),
    ],

    'endpoints' => [
        'sandbox' => env('TIRAMIS_SANDBOX_URL', 'https://sandbox.tira.go.tz/api/v1'),
        'production' => env('TIRAMIS_PRODUCTION_URL', 'https://tira.go.tz/api/v1'),
    ],

    'digital_signature' => [
        'enabled' => env('TIRAMIS_SIGNATURE_ENABLED', false),
        'cert_path' => env('TIRAMIS_CERT_PATH', storage_path('app/tiramis/cert.p12')),
        'cert_password' => env('TIRAMIS_CERT_PASSWORD', ''),
        'algorithm' => 'sha1WithRSA',
        'encoding' => 'BASE64',
        'public_key_path' => env('TIRAMIS_PUBLIC_KEY_PATH', storage_path('app/tiramis/tira-public.cer')),
    ],

    'timeout' => env('TIRAMIS_TIMEOUT', 60),

    'retry_on_failure' => env('TIRAMIS_RETRY', true),

    'max_retries' => env('TIRAMIS_MAX_RETRIES', 3),

    'default_report_type' => env('TIRAMIS_DEFAULT_REPORT', 'claims'),

    'sync_interval' => env('TIRAMIS_SYNC_INTERVAL', 'daily'),

    'company_code_prefix' => env('TIRAMIS_COMPANY_PREFIX', 'TZ'),

    'sales_code_prefix' => env('TIRAMIS_SALES_PREFIX', 'SL'),

    // ==================== KYC & NIDA VERIFICATION ====================

    'kyc' => [
        'enabled' => env('TIRAMIS_KYC_ENABLED', true),
        'nida_base_url' => env('TIRAMIS_NIDA_URL', ''),
        'nida_api_key' => env('TIRAMIS_NIDA_API_KEY', ''),
        'verify_endpoint' => '/kyc/verify',
        'lookup_endpoint' => '/kyc/lookup',
        'cache_ttl' => env('TIRAMIS_KYC_CACHE_TTL', 3600),
    ],

    // ==================== VEHICLE LOOKUP ====================

    'vehicle' => [
        'enabled' => env('TIRAMIS_VEHICLE_ENABLED', true),
        'lookup_endpoint' => '/vehicle/lookup',
        'verify_endpoint' => '/vehicle/verify',
    ],

    // ==================== TUNNEL / LOCAL SERVER ====================

    'tunnel' => [
        'enabled' => env('TIRAMIS_TUNNEL_ENABLED', false),
        'host' => env('TIRAMIS_TUNNEL_HOST', ''),
        'port' => env('TIRAMIS_TUNNEL_PORT', ''),
        'base_url' => env('TIRAMIS_TUNNEL_URL', ''),
        'auth_token' => env('TIRAMIS_TUNNEL_AUTH_TOKEN', ''),
    ],

    // ==================== PAYMENT INTEGRATION ====================

    'payment' => [
        'enabled' => env('TIRAMIS_PAYMENT_ENABLED', true),
        'submit_endpoint' => '/payment/submit',
        'verify_endpoint' => '/payment/verify',
    ],

    // TIRAMIS response codes (TIRA001 - TIRA234)
    'response_codes' => [
        'TIRA001' => 'Successful',
        'TIRA002' => 'Failure',
        'TIRA003' => 'Invalid client key',
        'TIRA004' => 'An error occurred while processing',
        'TIRA005' => 'Invalid or incomplete request data',
        'TIRA006' => 'Request could not be processed. Try again later',
        'TIRA007' => 'Requested data could not be found',
        'TIRA008' => 'Required request header information not provided',
        'TIRA009' => 'Request header information mismatch client identification parameters',
        'TIRA010' => 'Server internal communication failure',
        'TIRA011' => 'Client system configuration not found',
        'TIRA012' => 'Inactive or disabled Client system configuration',
        'TIRA013' => 'Inactive or invalid Client',
        'TIRA014' => 'Client PKI certificate file not found in specified path',
        'TIRA015' => 'Bad or missing Client PKI configurations',
        'TIRA016' => 'Invalid request signature',
        'TIRA017' => 'Invalid client system call back url',
        'TIRA018' => 'Invalid company code',
        'TIRA019' => 'Invalid cover note type',
        'TIRA020' => 'Invalid covernote start date',
        'TIRA021' => 'Invalid covernote end date',
        'TIRA022' => 'Invalid insurance company',
        'TIRA023' => 'Invalid insurance transaction company',
        'TIRA024' => 'Duplicate insurance covernote number or covernote identification number',
        'TIRA025' => 'Invalid or inactive insurance transaction sale point',
        'TIRA026' => 'Invalid or inactive insurance transaction product',
        'TIRA027' => 'Invalid or inactive insurance transaction currency',
        'TIRA028' => 'Invalid transaction exchange rate',
        'TIRA029' => 'Invalid insurance sum insured equivalent amount',
        'TIRA030' => 'Invalid insurance covernote risk covered premium rate',
        'TIRA031' => 'Invalid insurance premium amount (premium before discount)',
        'TIRA032' => 'Invalid insurance tax code or tax type(s) charged',
        'TIRA033' => 'Invalid insurance tax type rates used',
        'TIRA034' => 'Invalid insurance tax type amount',
        'TIRA035' => 'Invalid insurance total taxes or premium including tax value',
        'TIRA036' => 'Invalid covernote reference number',
        'TIRA037' => 'Duplicate reinsurance declaration',
        'TIRA038' => 'Invalid reinsurance participant',
        'TIRA039' => 'Invalid coinsurance premium amount value',
        'TIRA040' => 'Invalid reinsurance participation share value',
        'TIRA041' => 'Invalid reinsurance participation type',
        'TIRA042' => 'Invalid insurer policy number',
        'TIRA043' => 'Invalid policy operative clause',
        'TIRA044' => 'Policy applied covernote(s) does not exist',
        'TIRA045' => 'Duplicate policy',
        'TIRA046' => 'Applied covernote(s) have policy',
        'TIRA047' => 'Duplicate policy applied covernote(s)',
        'TIRA048' => 'Notification content preparation failed',
        'TIRA049' => 'No content returned by client system',
        'TIRA050' => 'Error occurred while connecting to external system',
        'TIRA051' => 'Client system not allowed for inbound communication',
        'TIRA052' => 'Client system not allowed for outbound communication',
        'TIRA053' => 'Invalid claim notification report date',
        'TIRA054' => 'Invalid risk covered',
        'TIRA055' => 'Invalid premium charged after discount equivalent amount',
        'TIRA056' => 'Duplicate claim notification number',
        'TIRA057' => 'Invalid claim notification number',
        'TIRA058' => 'Claimant exists for the specified covernote',
        'TIRA059' => 'Invalid claim reference number',
        'TIRA060' => 'Duplicate claim intimation',
        'TIRA061' => 'Invalid claim intimation date',
        'TIRA062' => 'Invalid claim intimation number',
        'TIRA063' => 'Duplicate claim assessment number',
        'TIRA064' => 'Invalid claim assessment received date',
        'TIRA065' => 'Invalid claim approval date',
        'TIRA066' => 'Invalid claim adjustment date',
        'TIRA067' => 'Invalid claim offer communication date',
        'TIRA068' => 'Invalid claimant claim offer response date',
        'TIRA069' => 'Invalid offer reconciliation',
        'TIRA070' => 'Claim assessment for the payment not found',
        'TIRA071' => 'Duplicate claim payment number',
        'TIRA072' => 'Claim has already been paid',
        'TIRA073' => 'Invalid claim payment date',
        'TIRA074' => 'Invalid claim payment currency',
        'TIRA075' => 'Invalid claim payment amount',
        'TIRA076' => 'Duplicate claim rejection number',
        'TIRA077' => 'Invalid claim rejection date',
        'TIRA078' => 'Invalid claim rejection. Claim already paid',
        'TIRA079' => 'Invalid claim loss date',
        'TIRA080' => 'Invalid reinsurance broker',
        'TIRA081' => 'Invalid covernote type',
        'TIRA082' => 'Invalid previous covernote reference number',
        'TIRA083' => 'Invalid total premium including tax value',
        'TIRA084' => 'Invalid total premium excluding tax value',
        'TIRA085' => 'Invalid premium discount type',
        'TIRA086' => 'Invalid premium discount amount',
        'TIRA087' => 'Premium discount is not allowed for this type of cover',
        'TIRA088' => 'Invalid acknowledgement',
        'TIRA089' => 'Pending transaction waiting for processing',
        'TIRA090' => 'Active covernote with specified insurance product exists for this motor',
        'TIRA091' => 'Invalid risk covered premium after discount value',
        'TIRA092' => 'Invalid claimant details',
        'TIRA093' => 'Invalid claim assessment number',
        'TIRA094' => 'Invalid claim litigation reason',
        'TIRA095' => 'Invalid request identification number',
        'TIRA096' => 'Invalid client system code',
        'TIRA097' => 'Invalid covernote type',
        'TIRA098' => 'Invalid covernote number',
        'TIRA099' => 'Invalid covernote description',
        'TIRA100' => 'Invalid covernote operative clause',
        'TIRA101' => 'Invalid payment mode',
        'TIRA102' => 'Invalid commission paid',
        'TIRA103' => 'Invalid commission rate',
        'TIRA104' => 'Invalid value identifying if transaction is part of fleet or not',
        'TIRA105' => 'Invalid or duplicate fleet identification number',
        'TIRA106' => 'Invalid fleet size',
        'TIRA107' => 'Invalid total comprehensive insured motors value',
        'TIRA108' => 'Invalid fleet entry',
        'TIRA109' => 'Invalid insurance officer name',
        'TIRA110' => 'Invalid insurance officer title',
        'TIRA111' => 'Invalid insurance risk code',
        'TIRA112' => 'Invalid insurance sum insured amount',
        'TIRA113' => 'Invalid subject matter covered reference',
        'TIRA114' => 'Invalid subject matter covered description',
        'TIRA115' => 'Invalid insurance addon reference',
        'TIRA116' => 'Invalid insurance addon description',
        'TIRA117' => 'Invalid insurance addon premium amount',
        'TIRA118' => 'Invalid insurance addon premium rate',
        'TIRA119' => 'Invalid insurance addon premium excluding tax amount',
        'TIRA120' => 'Invalid insurance addon premium excluding tax equivalent amount',
        'TIRA121' => 'Invalid insurance addon premium including tax amount',
        'TIRA122' => 'Invalid insurance policyholder name',
        'TIRA123' => 'Invalid insurance policyholder birth date or company registration date',
        'TIRA124' => 'Invalid insurance policyholder type',
        'TIRA125' => 'Invalid identity number or company incorporation certificate number',
        'TIRA126' => 'Invalid identity type',
        'TIRA127' => 'Invalid gender',
        'TIRA128' => 'Invalid country or country code',
        'TIRA129' => 'Invalid region or state',
        'TIRA130' => 'Invalid district or county',
        'TIRA131' => 'Invalid street',
        'TIRA132' => 'Invalid phone number',
        'TIRA133' => 'Invalid fax number',
        'TIRA134' => 'Invalid address',
        'TIRA135' => 'Invalid email address',
        'TIRA136' => 'Invalid motor category',
        'TIRA137' => 'Invalid motor registration number',
        'TIRA138' => 'Invalid motor chassis number',
        'TIRA139' => 'Invalid motor make',
        'TIRA140' => 'Invalid motor model',
        'TIRA141' => 'Invalid motor model number',
        'TIRA142' => 'Invalid motor body type',
        'TIRA143' => 'Invalid motor color',
        'TIRA144' => 'Invalid motor engine number',
        'TIRA145' => 'Invalid motor engine capacity',
        'TIRA146' => 'Invalid motor fuel used',
        'TIRA147' => 'Invalid motor number of axles',
        'TIRA148' => 'Invalid motor axle distance',
        'TIRA149' => 'Invalid motor sitting capacity',
        'TIRA150' => 'Invalid motor year of manufacture',
        'TIRA151' => 'Invalid motor tare weight',
        'TIRA152' => 'Invalid motor gross weight',
        'TIRA153' => 'Invalid motor usage',
        'TIRA154' => 'Invalid motor owner name',
        'TIRA155' => 'Invalid motor owner category',
        'TIRA156' => 'Invalid motor owner address',
        'TIRA157' => 'Invalid policy special conditions',
        'TIRA158' => 'Invalid policy exclusions',
        'TIRA159' => 'Invalid insurance sticker number',
        'TIRA160' => 'Invalid reinsurance category',
        'TIRA161' => 'Invalid reinsurance participant or participant code',
        'TIRA162' => 'Invalid reinsurance participant type',
        'TIRA163' => 'Invalid reinsurance form',
        'TIRA164' => 'Invalid reinsurance type',
        'TIRA165' => 'Invalid reinsurance rebroker or rebroker code',
        'TIRA166' => 'Invalid reinsurance rebrokerage commission value',
        'TIRA167' => 'Invalid reinsurance commission value',
        'TIRA168' => 'Invalid reinsurance premium share value',
        'TIRA169' => 'Invalid reinsurance participation date',
        'TIRA170' => 'Invalid value identifying if claim form is dully filled or not',
        'TIRA171' => 'Invalid claim loss nature',
        'TIRA172' => 'Invalid claim loss type',
        'TIRA173' => 'Invalid claim loss location',
        'TIRA174' => 'Invalid claim estimated amount',
        'TIRA175' => 'Invalid claim reserved amount',
        'TIRA176' => 'Invalid claim reserve method',
        'TIRA177' => 'Invalid claim loss assessment option',
        'TIRA178' => 'Invalid claim assessor name',
        'TIRA179' => 'Invalid claim assessor identity number',
        'TIRA180' => 'Invalid claim assessor identity type',
        'TIRA181' => 'Invalid claimant name',
        'TIRA182' => 'Invalid claimant birth date',
        'TIRA183' => 'Invalid claimant category',
        'TIRA184' => 'Invalid claimant type',
        'TIRA185' => 'Invalid claimant identity number',
        'TIRA186' => 'Invalid claimant identity type',
        'TIRA187' => 'Invalid claim assessment report summary',
        'TIRA188' => 'Invalid claim assessment amount',
        'TIRA189' => 'Invalid claim approved amount',
        'TIRA190' => 'Invalid claim approval date',
        'TIRA191' => 'Invalid claim approval authority',
        'TIRA192' => 'Invalid value identifying if its claim reassessment or not',
        'TIRA193' => 'Invalid discharge voucher number',
        'TIRA194' => 'Duplicate discharge voucher',
        'TIRA195' => 'Invalid discharge voucher date',
        'TIRA196' => 'Invalid claim discharge voucher offer communication date',
        'TIRA197' => 'Invalid claim discharge voucher offer communicated amount',
        'TIRA198' => 'Invalid claim discharge voucher offer response date',
        'TIRA199' => 'Invalid claim discharge voucher offer adjustment date',
        'TIRA200' => 'Invalid claim discharge voucher offer adjustment reason',
        'TIRA201' => 'Invalid claim discharge voucher offer adjustment amount',
        'TIRA202' => 'Invalid claim discharge voucher offer reconciliation date',
        'TIRA203' => 'Invalid claim discharge voucher offer reconciliation reason',
        'TIRA204' => 'Invalid claim discharge voucher offer reconciliation amount',
        'TIRA205' => 'Invalid value identifying if offer was accepted or not',
        'TIRA206' => 'Invalid claim payment number',
        'TIRA207' => 'Invalid value identifying if claim parties were notified about claim payment or not',
        'TIRA208' => 'Invalid claim net premium earned',
        'TIRA209' => 'Invalid value identifying if claim resulted into litigation or not',
        'TIRA210' => 'Invalid claim rejection number',
        'TIRA211' => 'Invalid claim rejection reason',
        'TIRA212' => 'Invalid endorsement type',
        'TIRA213' => 'Invalid endorsement reason',
        'TIRA226' => 'Invalid premium discount rate',
        'TIRA227' => 'Invalid endorsement premium earned amount',
        'TIRA228' => 'Invalid value identifying premium is tax exempted or not',
        'TIRA229' => 'Invalid tax exemption type',
        'TIRA230' => 'Invalid tax exemption reference',
        'TIRA231' => 'Invalid motor type',
        'TIRA233' => 'Active covernote with specified motor details exists',
        'TIRA234' => 'Invalid fleet type',
    ],
];
