<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Premium Collections Report</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Arial', sans-serif;
            font-size: 10pt;
            line-height: 1.4;
            color: #333;
        }
        
        /* Watermark */
        body::before {
            content: "BIMAKWIK";
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%) rotate(-45deg);
            font-size: 100pt;
            font-weight: bold;
            color: rgba(200, 200, 200, 0.1);
            z-index: -1;
        }
        
        .header {
            text-align: center;
            margin-bottom: 20px;
            padding-bottom: 15px;
            border-bottom: 3px solid #0d6efd;
        }
        
        .company-name {
            font-size: 20pt;
            font-weight: bold;
            color: #0d6efd;
            margin-bottom: 5px;
        }
        
        .report-title {
            font-size: 16pt;
            font-weight: bold;
            color: #333;
            margin-top: 10px;
        }
        
        .info-box {
            background: #f8f9fa;
            padding: 10px;
            border-radius: 5px;
            margin-bottom: 20px;
            border-left: 4px solid #0d6efd;
        }
        
        .info-row {
            margin: 5px 0;
        }
        
        .info-label {
            font-weight: bold;
            display: inline-block;
            width: 150px;
        }
        
        .stats-grid {
            display: table;
            width: 100%;
            margin-bottom: 20px;
        }
        
        .stat-box {
            display: table-cell;
            width: 33.33%;
            padding: 10px;
            text-align: center;
            background: #f8f9fa;
            border: 1px solid #dee2e6;
        }
        
        .stat-label {
            font-size: 9pt;
            color: #666;
            margin-bottom: 5px;
        }
        
        .stat-value {
            font-size: 14pt;
            font-weight: bold;
            color: #0d6efd;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }
        
        table th {
            background: #0d6efd;
            color: white;
            padding: 8px 5px;
            text-align: left;
            font-size: 9pt;
            font-weight: bold;
        }
        
        table td {
            padding: 6px 5px;
            border-bottom: 1px solid #e9ecef;
            font-size: 9pt;
        }
        
        table tr:nth-child(even) {
            background: #f8f9fa;
        }
        
        .badge {
            display: inline-block;
            padding: 3px 8px;
            border-radius: 10px;
            font-size: 8pt;
            font-weight: bold;
        }
        
        .badge-success {
            background: #d4edda;
            color: #155724;
        }
        
        .badge-warning {
            background: #fff3cd;
            color: #856404;
        }
        
        .badge-danger {
            background: #f8d7da;
            color: #721c24;
        }
        
        .footer {
            margin-top: 30px;
            padding-top: 15px;
            border-top: 2px solid #e9ecef;
            text-align: center;
            font-size: 8pt;
            color: #666;
        }
        
        .page-break {
            page-break-after: always;
        }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="header">
        <div class="company-name">BIMAKWIK</div>
        <div style="font-size: 10pt; color: #666;">Insurance Aggregation Platform</div>
        <div class="report-title">PREMIUM COLLECTIONS REPORT</div>
    </div>
    
    <!-- Document Info -->
    <div class="info-box">
        <div class="info-row">
            <span class="info-label">Generated Date:</span>
            <span>{{ $generatedDate }}</span>
        </div>
        <div class="info-row">
            <span class="info-label">Generated Time:</span>
            <span>{{ $generatedTime }}</span>
        </div>
        <div class="info-row">
            <span class="info-label">Generated By:</span>
            <span>{{ $generatedBy }}</span>
        </div>
        <div class="info-row">
            <span class="info-label">Total Records:</span>
            <span>{{ $collections->count() }} transactions</span>
        </div>
    </div>
    
    <!-- Statistics -->
    <div class="stats-grid">
        <div class="stat-box">
            <div class="stat-label">Total Collected</div>
            <div class="stat-value">TZS {{ number_format($totalCollected, 2) }}</div>
        </div>
        <div class="stat-box">
            <div class="stat-label">Today's Collections</div>
            <div class="stat-value">TZS {{ number_format($todayCollections, 2) }}</div>
        </div>
        <div class="stat-box">
            <div class="stat-label">Total Transactions</div>
            <div class="stat-value">{{ number_format($collections->count()) }}</div>
        </div>
    </div>
    
    <!-- Transactions Table -->
    <h3 style="margin: 20px 0 10px 0; color: #0d6efd; font-size: 12pt;">Premium Collections</h3>
    <table>
        <thead>
            <tr>
                <th>TXN ID</th>
                <th>Customer</th>
                <th>Type</th>
                <th>Amount</th>
                <th>Method</th>
                <th>Status</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            @forelse($collections as $transaction)
            <tr>
                <td>TXN-{{ $transaction->id }}</td>
                <td>{{ $transaction->user->name ?? 'N/A' }}</td>
                <td>{{ $transaction->type ?? 'Premium' }}</td>
                <td><strong>TZS {{ number_format($transaction->amount ?? 0, 2) }}</strong></td>
                <td>{{ $transaction->payment_method ?? 'M-Pesa' }}</td>
                <td>
                    @php
                        $status = $transaction->status ?? 'completed';
                        $badgeClass = $status == 'completed' || $status == 'paid' ? 'success' : ($status == 'pending' ? 'warning' : 'danger');
                    @endphp
                    <span class="badge badge-{{ $badgeClass }}">{{ ucfirst($status) }}</span>
                </td>
                <td>{{ $transaction->created_at ? $transaction->created_at->format('M d, Y') : 'N/A' }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="7" style="text-align: center; padding: 20px;">No transactions found</td>
            </tr>
            @endforelse
        </tbody>
    </table>
    
    <!-- Summary -->
    <div style="margin-top: 30px; background: #f8f9fa; padding: 15px; border-radius: 5px;">
        <h4 style="color: #0d6efd; margin-bottom: 10px;">Summary</h4>
        <table style="border: none;">
            <tr>
                <td style="border: none; font-weight: bold;">Total Premium Collections:</td>
                <td style="border: none; text-align: right;"><strong>TZS {{ number_format($totalCollected, 2) }}</strong></td>
            </tr>
            <tr>
                <td style="border: none; font-weight: bold;">Number of Transactions:</td>
                <td style="border: none; text-align: right;"><strong>{{ number_format($collections->count()) }}</strong></td>
            </tr>
            <tr>
                <td style="border: none; font-weight: bold;">Average Transaction:</td>
                <td style="border: none; text-align: right;"><strong>TZS {{ $collections->count() > 0 ? number_format($totalCollected / $collections->count(), 2) : '0.00' }}</strong></td>
            </tr>
        </table>
    </div>
    
    <!-- Footer -->
    <div class="footer">
        <p><strong>CONFIDENTIAL DOCUMENT</strong></p>
        <p>This report contains confidential information and is intended solely for authorized personnel.</p>
        <p>Unauthorized copying, distribution, or use is strictly prohibited.</p>
        <p style="margin-top: 10px;">
            <strong>Bimakwik Insurance Aggregation Platform</strong><br>
            © {{ date('Y') }} Bimakwik Ltd. All Rights Reserved.
        </p>
    </div>
</body>
</html>
