<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\AuditComplianceReport;
use App\Models\AuditLog;
use App\Models\ComplianceCheck;
use Illuminate\Pagination\LengthAwarePaginator;

class GovernanceController extends Controller
{
    public function compliance()
    {
        try {
            // Combine compliance-related models
            $auditReports = AuditComplianceReport::latest()->get();
            $complianceChecks = ComplianceCheck::latest()->get();
            
            // Merge all compliance data
            $allReports = $auditReports->merge($complianceChecks);
            
            // Paginate manually using LengthAwarePaginator
            $page = request()->get('page', 1);
            $perPage = 20;
            $offset = ($page - 1) * $perPage;
            $paginatedItems = $allReports->slice($offset, $perPage)->values();
            
            $reports = new LengthAwarePaginator(
                $paginatedItems,
                $allReports->count(),
                $perPage,
                $page,
                ['path' => request()->url(), 'query' => request()->query()]
            );
            
        } catch (\Exception $e) {
            $reports = new LengthAwarePaginator([], 0, 20);
        }
        return view('admin.governance.compliance', compact('reports'));
    }

    public function analytics()
    {
        return view('admin.governance.analytics');
    }

    public function communications()
    {
        try {
            // Use empty paginator since Communication model doesn't exist
            $communications = new LengthAwarePaginator([], 0, 20);
        } catch (\Exception $e) {
            $communications = new LengthAwarePaginator([], 0, 20);
        }
        return view('admin.governance.communications', compact('communications'));
    }
    
    public function exportReport($id)
    {
        try {
            // Get report data
            $report = AuditComplianceReport::findOrFail($id);
            
            // Create CSV export
            $filename = 'Compliance_Report_' . $report->id . '_' . now()->format('Ymd_His') . '.csv';
            
            $headers = [
                'Content-Type' => 'text/csv',
                'Content-Disposition' => 'attachment; filename="' . $filename . '"',
            ];
            
            $callback = function() use ($report) {
                $file = fopen('php://output', 'w');
                
                // Report header
                fputcsv($file, ['BIMAKWIK COMPLIANCE REPORT']);
                fputcsv($file, []);
                
                // Report details
                fputcsv($file, ['Report ID', $report->id]);
                fputcsv($file, ['Report Type', $report->report_type ?? 'Compliance Report']);
                fputcsv($file, ['Status', $report->status ?? 'Pending']);
                fputcsv($file, ['Description', $report->description ?? 'N/A']);
                fputcsv($file, ['Created Date', $report->created_at ? $report->created_at->format('Y-m-d H:i:s') : 'N/A']);
                fputcsv($file, []);
                
                // Summary
                fputcsv($file, ['COMPLIANCE SUMMARY']);
                fputcsv($file, ['Generated By', auth()->user()->name ?? 'System']);
                fputcsv($file, ['Generated Date', now()->format('Y-m-d H:i:s')]);
                fputcsv($file, []);
                
                // Footer
                fputcsv($file, ['CONFIDENTIAL DOCUMENT']);
                fputcsv($file, ['© ' . date('Y') . ' Bimakwik Ltd. All Rights Reserved']);
                
                fclose($file);
            };
            
            return response()->stream($callback, 200, $headers);
            
        } catch (\Exception $e) {
            return redirect()->back()->with('error', 'Failed to generate export: ' . $e->getMessage());
        }
    }
}
